QuarryIQ/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin





urlpatterns = [
    path('admin/', admin.site.urls),
    path('csp-report-endpoint/', views.csp_report, name='csp_report'),

    # Sagitta Nova website
    path("", views.Home, name='Home'),
    path("Contact/", views.Contact, name='Contact'),

    # Quarry IQ application
    # Login / Password
    path("Login/", auth_views.LoginView.as_view(template_name='QuarryIQ/Login.html'), name='Login'),
    path('Logout/', auth_views.LogoutView.as_view(template_name='QuarryIQ/Logout.html'), name='Logout'),
    path('User_Profile/', views.User_Profile_view, name='User_Profile'),


    # Admin Portal
    path('Admin_Portal', views.Admin_Portal_view, name='Admin_Portal'),
    path('Delete_Access/<int:association_id>/', views.Delete_Access_bridge, name='Delete_Access'),
    path('Delete_Project/<str:project_id>/', views.Delete_Project_bridge, name='Delete_Project'),
    path('New_Project/General_Info/', views.New_Project_General_Info_view, name='New_Project_General_Info'),
    path('New_Project/General_Info_bridge/<str:project_id>/', views.General_Info_to_Data_Cleaning_bridge, name='General_Info_to_Data_Cleaning'),
    path('New_Project/Upload_Data/<str:project_id>/', views.Upload_Data, name='Upload_Data'),

    path('Model_Portal', views.Model_Portal_view, name='Model_Portal'),
    path('flush-uploaded-glpk/', views.Flush_uploaded_glpk, name='flush_uploaded_glpk'),


    # Project List
    path('Project_List/', views.Project_List_view, name='Project_List'),
    path('Modify_Project_Information/<str:project_id>/', views.Modify_Information_view, name='Modify_Information'),


    # Existing Projects / Data Portal
    path('Existing_Projects/Data_Portal/<str:project_id>/', views.Data_Portal_view, name='Data_Portal'),

    # Existing Projects / Data Portal / Product Cleaning
    path('Existing_Projects/Data_Portal/Product_Cleaning/<str:project_id>/', views.Product_Cleaning_view, name='Product_Cleaning'),
    path('Transfer_point/<str:project_id>/', views.Handle_modified_products_view, name='Handle_modified_products'),

    # Existing Projects / Data Portal / Heatmaps
    path('Existing_Projects/Data_Portal/Heatmaps/Heatmap_Portal/<str:project_id>/', views.Heatmap_Portal_view, name='Heatmap_Portal'),
    path('Existing_Projects/Data_Portal/Heatmaps/Heatmap_all_product_group/<str:project_id>/', views.Heatmap_all_product_groups_view, name='Heatmap_all_product_groups'),
    path('Existing_Projects/Data_Portal/Heatmaps/Heatmap_product_group/<str:product_group>/<str:project_id>/', views.Heatmap_product_group_view, name='Heatmap_product_group'),

    # Existing Projects / Data Portal / Streamsmaps
    path('Existing_Projects/Data_Portal/Heatmaps/Streams_map_Portal/<str:project_id>/', views.Streamsmap_Portal_view, name='Streamsmap_Portal'),
    path('Existing_Projects/Data_Portal/Streamsmaps/Streams_maps_baseline_all_incoterms/<str:project_id>/', views.Streamsmap_baseline_all_incoterms_view, name='Streamsmap_baseline_all_incoterms'),
    path('Existing_Projects/Data_Portal/Streamsmaps/Streams_maps_baseline_incoterm/<str:incoterm>/<str:project_id>/', views.Streams_maps_baseline_incoterm_view, name='Streams_maps_baseline_incoterm_view'),

    # Existing Projects / Data Portal / P4P Portal
    path('Existing_Projects/Data_Portal/P4P_Portal/<str:project_id>/', views.P4P_Portal_view, name='P4P_Portal'),
    path('Existing_Projects/Data_Portal/P4P_Portal/Cluster_to_box/<str:project_id>/<str:quarry_id>/', views.P4P_Cluster_to_box_view, name='P4P_Cluster_to_box'),
    path('Existing_Projects/Data_Portal/P4P_Portal/Cluster_to_box_bridge/<str:project_id>/<str:quarry_id>/', views.P4P_Cluster_to_box_to_Product_list_bridge, name='P4P_Cluster_to_box_to_Product_list'),
    path('Existing_Projects/Data_Portal/P4P_Portal/Product_list/<str:project_id>/<str:quarry_id>/', views.P4P_Product_list_view, name='P4P_Product_list'),
    path('Existing_Projects/Data_Portal/P4P_Portal/Product_list_bridge/<str:project_id>/<str:quarry_id>/', views.P4P_Product_list_to_PL_allocation_bridge, name='P4P_Product_list_to_PL_allocation'),
    path('Existing_Projects/Data_Portal/P4P_Portal/PL_allocation/<str:project_id>/<str:quarry_id>/', views.P4P_PL_allocation_view, name='P4P_PL_allocation'),
    path('Existing_Projects/Data_Portal/P4P_Portal/Electricity_calculator/<str:project_id>/<str:quarry_id>/', views.Electricity_calculator_view, name='P4P_Elec_calculator'),
    path('Existing_Projects/Data_Portal/P4P_Portal/PL_allocation_bridge/<str:project_id>/<str:quarry_id>/', views.P4P_PL_allocation_to_Results_bridge, name='P4P_PL_allocation_to_Results'),
    path('Existing_Projects/Data_Portal/P4P_Portal/P4P_Results/<str:project_id>/<str:quarry_id>/', views.P4P_Results_view, name='P4P_Results'),

    # Existing Projects / Data Portal / B4P Portal
    path('Existing_Projects/Data_Portal/B4C_Portal/<str:project_id>/', views.B4C_Portal_view, name='B4C_Portal'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Product_Composition/<str:project_id>/<str:quarry_id>/', views.B4C_Product_Composition_view, name='B4C_Product_Composition'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Product_Composition_bridge/<str:project_id>/<str:quarry_id>/', views.B4C_Product_Composition_to_Production_Balance_bridge, name='B4C_Product_Composition_to_Production_Balance'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Production_Balance/<str:project_id>/<str:quarry_id>/', views.B4C_Production_Balance_view, name='B4C_Production_Balance_view'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Production_Balance_bridge/<str:project_id>/<str:quarry_id>/', views.B4C_Production_Balance_to_Results_bridge, name='B4C_Production_Balance_to_Results'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Results/<str:project_id>/<str:quarry_id>/', views.B4C_Results_view, name='B4C_Results'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Simulator/<str:project_id>/<str:quarry_id>/', views.B4C_Simulator_view, name='B4C_Simulator'),
    path('Existing_Projects/Data_Portal/B4C_Portal/Simulator_bridge/<str:project_id>/<str:quarry_id>/', views.B4C_Simulator_bridge, name='B4C_Simulator_bridge'),

    # Existing Projects / Data Portal / FarSeer Portal
    path('Existing_Projects/Data_Portal/FarSeer_Portal/<str:project_id>/', views.FarSeer_Portal_view, name='FarSeer_Portal'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/<str:project_id>/<str:quarry_id>/', views.FarSeer_Clear_Data, name='FarSeer_Clear_Data'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Informations/<str:project_id>/<str:quarry_id>/', views.FarSeer_Information_view, name='FarSeer_Information'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Informations_bridge/<str:project_id>/<str:quarry_id>/', views.FarSeer_Information_to_Forecast_bridge, name='FarSeer_Information_to_Forecast'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Forecast/<str:project_id>/<str:quarry_id>/', views.FarSeer_Forecast_view, name='FarSeer_Forecast'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Forecast_bridge/<str:project_id>/<str:quarry_id>/', views.FarSeer_Forecast_to_Results_bridge, name='FarSeer_Forecast_to_Results'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Results_Summary/<str:project_id>/<str:quarry_id>/', views.FarSeer_Results_Summary_view, name='FarSeer_Results_Summary'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Results_Summary_Meet_All_Sales/<str:project_id>/<str:quarry_id>/', views.FarSeer_Results_Meet_All_Sales_view, name='FarSeer_Results_Meet_All_Sales'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Results_Summary_Meet_Forced_Sales/<str:project_id>/<str:quarry_id>/', views.FarSeer_Results_Meet_Forced_Sales_view, name='FarSeer_Results_Meet_Forced_Sales'),
    path('Existing_Projects/Data_Portal/FarSeer_Portal/Results_Summary_MaxGM/<str:project_id>/<str:quarry_id>/', views.FarSeer_Results_MaxGM_view, name='FarSeer_Results_MaxGM'),

    # Existing Projects / Data Portal / Network Optimisation
    path('Existing_Projects/Data_Portal/Network_Optimisation_Portal/<str:project_id>/', views.Network_Optimisation_Portal_view, name='Network_Optimisation_Portal'),
    path('Existing_Projects/Data_Portal/Network_Optimisation_Portal/Delete_Scenario/<str:project_id>/<str:scenario_id>/', views.Network_Optimisation_Clear_Scenario, name='Network_Optimisation_Clear_Scenario'),

    path('Existing_Projects/Data_Portal/Network_Optimisation_Baseline_Information/<str:project_id>/', views.NO_Baseline_Information_view, name='NO_Baseline_Information'),
    path('Existing_Projects/Data_Portal/Network_Optimisation_Baseline_Information_bridge/<str:project_id>/', views.NO_Baseline_Information_to_Results_bridge, name='NO_Baseline_Information_to_Results'),
    path('Existing_Projects/Data_Portal/Network_Optimisation_Baseline_Results/<str:project_id>/', views.NO_Baseline_Results_view, name='NO_Baseline_Results'),

    path('Existing_Projects/Data_Portal/Network_Optimisation_Scenario_Information/<str:project_id>/<str:scenario_id>/', views.NO_Scenario_Information_view, name='NO_Scenario_Information'),
    path('Existing_Projects/Data_Portal/Network_Optimisation_Scenario_Information_bridge/<str:project_id>/<str:scenario_id>/', views.NO_Scenario_Information_to_Results_bridge, name='NO_Scenario_Information_to_Results'),
    path('Existing_Projects/Data_Portal/Network_Optimisation_Scenario_Results/<str:project_id>/<str:scenario_id>/', views.NO_Scenario_Results_view, name='NO_Scenario_Results'),


]

QuarryIQ/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
import uuid
import shutil
from django.conf import settings




class ProjectData(models.Model):
    project_id = models.CharField(max_length=50, unique=True)
    project_company = models.CharField(max_length=50, default='')
    project_name = models.CharField(max_length=50)
    project_time_period = models.CharField(max_length=20)
    currency = models.CharField(max_length=10)
    EXWLocation = models.BooleanField(default=False)
    filtered_df_json = models.TextField(default='{}')
    distances_df_json = models.TextField(default='{}')
    modified_transactions_df_json = models.TextField(default='{}')
    modified_transactions_day_df_json = models.TextField(default='{}')
    quarries = models.ManyToManyField('Quarry')
    # Network Optimisation
    baseline_infoTable_df_json = models.TextField(default='{}')
    radiusTable_df_json = models.TextField(default='{}')
    transport_cost_df_json = models.TextField(default='{}')
    reduced_customers_df_json = models.TextField(default='{}')
    small_customers_df_json = models.TextField(default='{}')
    NO_Baseline_Raw_Results_df_json = models.TextField(default='{}')
    Transport_Cost_per_Customer_df_json = models.TextField(default='{}')
    NO_Baseline_Customer_Results_df_json = models.TextField(default='{}')
    NO_Baseline_Gross_Sales = models.IntegerField(default=0)
    NO_Baseline_Done = models.BooleanField(default=False)


    def save(self, *args, **kwargs):
        # Generate a unique project ID only if it's a new instance
        if not self.pk:
            self.project_id = uuid4().hex
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Delete the associated folder
        shutil.rmtree(self.Existing_Projects_Data_Portal_path(), ignore_errors=True)
        super().delete(*args, **kwargs)

    def Existing_Projects_Data_Portal_path(self):
        return os.path.join(settings.BASE_DIR, 'QuarryIQ', 'templates', 'QuarryIQ', 'Project_Data', self.project_id)
    def Heatmap_folder_path(self):
        return os.path.join(settings.BASE_DIR, 'QuarryIQ', 'templates', 'QuarryIQ', 'Project_Data', self.project_id, 'Heatmaps')
    def Streamsmap_folder_path(self):
        return os.path.join(settings.BASE_DIR, 'QuarryIQ', 'templates', 'QuarryIQ', 'Project_Data', self.project_id, 'Streamsmaps')

class Quarry(models.Model):
    quarry_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, default='')
    year = models.CharField(max_length=25, default='')
    # P4P
    clusterToBox_df_json = models.TextField(default='{}')
    clusterToBox_df_change = models.BooleanField(default=False)
    productSalesVolume_df_json = models.TextField(default='{}')
    productAggLevy_df_json = models.TextField(default='{}')
    productProdVolume_df_json = models.TextField(default='{}')
    productProductCluster_df_json = models.TextField(default='{}')
    costBoxProdVolume_df_json = models.TextField(default='{}')
    productListFull_df_json = models.TextField(default='{}')
    PLAllocationData_df_json = models.TextField(default='{}')
    P4PFullSummary_df_json = models.TextField(default='{}')
    # B4C
    productComposition_df_json = models.TextField(default='{}')
    constituentModesBalance_df_json = models.TextField(default='{}')
    capacityModes_df_json = models.TextField(default='{}')
    # B4C Simulator
    salesSimulation_df_json = models.TextField(default='{}')
    minVC_Simulation_Table_df_json = models.TextField(default='{}')
    modes_Hours_minVC_Simulation_df_json = models.TextField(default='{}')
    maxGM_Simulation_Table_df_json = models.TextField(default='{}')
    modes_Hours_maxGM_Simulation_df_json = models.TextField(default='{}')
    # FarSeer
    startingMonth = models.CharField(max_length=50, default='')
    finalMonth = models.CharField(max_length=50, default='')
    FarSeer_stockInfo_df_json = models.TextField(default='{}')
    maxOpeningHours_df_json = models.TextField(default='{}')
    salesForecast_df_json = models.TextField(default='{}')
    FarSeer_meetAllSales_results_df_json = models.TextField(default='{}')
    FarSeer_meetAllSales_hours_df_json = models.TextField(default='{}')
    FarSeer_meetForcedSales_results_df_json = models.TextField(default='{}')
    FarSeer_meetForcedSales_hours_df_json = models.TextField(default='{}')
    FarSeer_maxGM_results_df_json = models.TextField(default='{}')
    FarSeer_maxGM_hours_df_json = models.TextField(default='{}')
    FarSeer_MeetAllSales_OptimisationSuccess = models.BooleanField(default=True)
    FarSeer_MeetForcedSales_OptimisationSuccess = models.BooleanField(default=True)
    FarSeer_MaxGM_OptimisationSuccess = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Scenario(models.Model):
    OPTIMISATION_CHOICES = [
        ('meeting_all_sales', 'Meeting All Sales'),
        ('max_gross_margin', 'Maximizing Gross Margin'),
    ]

    scenario_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(ProjectData, on_delete=models.CASCADE, related_name='scenarios')
    scenario_name = models.CharField(max_length=100)
    optimisation_type = models.CharField(max_length=20, choices=OPTIMISATION_CHOICES, default='meeting_all_sales')
    scenario_infoTable_df_json = models.TextField(default='{}')
    NO_Scenario_Raw_Results_df_json = models.TextField(default='{}')
    NO_Scenario_Customer_Results_df_json = models.TextField(default='{}')
    NO_Scenario_Done = models.BooleanField(default=False)


    def __str__(self):
        return self.scenario_name


class ProjectAccess(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    projects = models.ManyToManyField(ProjectData)

    def __str__(self):
        return f"{self.user.username}"



class UploadedGLPK(models.Model):
    original_file_name = models.CharField(max_length=255)
    encrypted_content = models.BinaryField(default=b'')  # Store only encrypted content
    upload_date = models.DateTimeField(auto_now_add=True)
    uploaded_file_name = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.original_file_name

QuarryIQ/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

QuarryIQ/templates/QuarryIQ/Existing_Projects/Data_Portal/Network_Optimisation_Portal/Network_Optimisation_Portal.html
{% extends 'QuarryIQ/base.html' %}

{% block content %}
<title>Quarry IQ - Network Optimisation Portal</title>

<h2>Quarry IQ - Network Optimisation Portal</h2>
<h4>Project: {{ project_name }} {{ project_time_period }}</h4>

<table><tr><th class="empty"></th><th class="empty"></th></tr></table>
<table><tr><th class="empty"></th><th class="empty"></th></tr></table>
<table><tr><th class="empty"></th><th class="empty"></th></tr></table>


    <table class="table">
        <thead>
            <tr>
                <th style="vertical-align: middle;">Scenario Name</th>
                <th style="vertical-align: middle;">Optimisation Type</th>
                {% if is_editor %}
                <th style="vertical-align: middle;">Edition</th>
                {% endif %}
                {% if NO_Baseline_Done %}
                <th style="vertical-align: middle;">Results</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="vertical-align: middle;">Baseline</td>
                <td style="vertical-align: middle;">Meeting All Sales</td>

                {% if is_editor %}
                <td style="vertical-align: middle;">
                    <form action="{% url 'NO_Baseline_Information' project_id=project_data.project_id %}" method="get">
                        <button type="submit" class="btn btn-outline-dark" style="width: 250px;">Edit</button>
                    </form>
                </td>
                {% endif %}

                {% if NO_Baseline_Done %}
                <td style="vertical-align: middle;">
                    <form action="{% url 'NO_Baseline_Results' project_id=project_data.project_id %}" method="get" onsubmit="showLoadingSpinner()">
                        <button type="submit" class="btn btn-warning" style="width: 250px;">Results</button>
                    </form>
                </td>
                {% endif %}
            </tr>

            {% for scenario in scenarios %}
            <tr>
                <td style="vertical-align: middle;">{{ scenario.scenario_name }}</td>

                {% if not scenario.NO_Scenario_Done %}
                <td style="vertical-align: middle;"></td>
                {% else %}
                <td style="vertical-align: middle;">{{ scenario.get_optimisation_type_display }}</td>
                {% endif %}

                {% if is_editor %}
                <td style="vertical-align: middle;">
                    <form action="{% url 'NO_Scenario_Information' project_id=project_data.project_id scenario_id=scenario.scenario_id %}" method="get">
                        <button type="submit" class="btn btn-outline-dark" style="width: 250px;">Edit</button>
                    </form>
                </td>
                {% endif %}

                {% if not scenario.NO_Scenario_Done %}
                <td style="vertical-align: middle;"></td>
                {% else %}
                <td style="vertical-align: middle;">
                    <form action="{% url 'NO_Scenario_Results' project_id=project_data.project_id scenario_id=scenario.scenario_id %}" method="get" onsubmit="showLoadingSpinner()">
                        <button type="submit" class="btn btn-warning" style="width: 250px;">Results</button>
                    </form>
                </td>
                {% endif %}

                {% if is_editor %}
                <td style="vertical-align: middle;">
                    <form action="{% url 'Network_Optimisation_Clear_Scenario' project_id=project_data.project_id scenario_id=scenario.scenario_id %}" method="post" onsubmit="confirmDelete(event)">
                        {% csrf_token %}
                        <input type="hidden" name="project_id" value="{{ project_data.project_id }}">
                        <input type="hidden" name="scenario_id" value="{{ scenario.scenario_id }}">
                        <button type="submit" class="btn btn-outline-danger" style="width: 250px;">Delete Scenario</button>
                    </form>
                </td>
                {% endif %}
            </tr>
            {% endfor %}

            <tr><td class="empty"></td></tr>
            {% if is_editor and NO_Baseline_Done %}
            <tr>
                <td class="empty" style="vertical-align: middle;">
                    <form id="scenarioForm" method="post" action="{% url 'Network_Optimisation_Portal' project_id=project_data.project_id %}" style="display: none;">
                        {% csrf_token %}
                        <input type="hidden" id="scenarioNameInput" name="scenario_name">
                    </form>
                    <button type="button" class="btn btn-outline-success" style="width: 250px;" onclick="promptScenarioName()">Add New Scenario</button>
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>


<input type="hidden" id="scenarioCount" value="{{ scenarios.count }}">


<script>
function promptScenarioName() {
    var scenarioCount = document.getElementById('scenarioCount').value;
    if (scenarioCount >= 10) {
        alert('You cannot create more than 10 scenarios.');
        return;
    }

    var scenarioName = prompt("Please specify scenario name:");
    if (scenarioName) {
        document.getElementById('scenarioNameInput').value = scenarioName;
        document.getElementById('scenarioForm').submit();
    }
}

function confirmDelete(event) {
        if (!confirm("Are you sure you want to delete this scenario?")) {
            event.preventDefault();
        }
    }
</script>


{% endblock content %}